services:
  # PHP Frontend
  web:
    build: ./php
    ports:
      - "8080:80"
    volumes:
      - ./php:/var/www/html
    depends_on:
      - db
      - logic-api

  frontend:
    build: ./html
    ports:
      - "8081:80"
    volumes:
      - ./html:/var/www/html


  # Python Logic (FastAPI)
  logic-api:
    build: ./python
    volumes:
      - ./python:/app
    ports:
      - "8000:8000"

  # MySQL Database
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: studyguide_db
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"

  adminer:
      image: adminer
      restart: always
      ports:
        - 8085:8080